name: 'Docker Image CI'
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 'Log in to Docker Hub'
      run: echo ${{ secrets.DockerHubPassword }} | docker login -u kjjanak --password-stdin
    - name: 'Build the Docker image'
      run: docker build -f Dockerfile -t kjjanak/kjjanak-resume .
    - name: 'Push base image'
      run: docker push kjjanak/kjjanak-resume
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been built.'